_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e4e646af-4019-4662-8099-0ba9ce950c74
name: 'Drupal 10 Experimental'
mail: sergey.gabrielyan1998@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
